export default {
    TYPE_ADMIN: "TYPE_ADMIN",
    TYPE_COMP: "TYPE_COMP",
    TYPE_COUNTRY: "TYPE_COUNTRY",
    TYPE_LANGUIGE: "TYPE_LANGUIGE",
    TYPE_QNA: "TYPE_QNA",
    TYPE_CAR: "TYPE_CAR",
    STATE_ACCOUNT: "STATE_ACCOUNT",
    STATE_JOURNEY: "STATE_JOURNEY",
    STATE_RESERVE: "STATE_RESERVE",
    CONTRACT_TYPE: "CONTRACT_TYPE",
    CONTRACT_STATE: "CONTRACT_STATE",
}